---
# I currently have 1 UniFi AP's in my home:
#   - Located in the hallway.
#
# I have a UniFi controller running 24/7 in a docker container.

# https://www.home-assistant.io/components/device_tracker.unifi/
#
##unifi:
##  controllers:
##    - host: !secret unifi_host
##      username: !secret unifi_username
##      password: !secret unifi_password
##      site: !secret unifi_site
##      dont_track_devices: true
##      dont_track_wired_clients: true
##      ssid_filter:
##        - 'HomeSSID'
##        - 'IoTSSID'

# Since this is an internal connection, the SSL connection won't verify.
# So lets ignore the fact that the cert is invalid for the above host.
# I do resolve domains locally so could use verified ssl however host will only take an ip address - need to confirm.
##verify_ssl: false

# Authentication credentials
##username: !secret device_tracker_unifi_username
##password: !secret device_tracker_unifi_password

# I really don't want to track each device that enters my WiFi
##new_device_defaults:
##  track_new_devices: false
##  hide_if_away: false

##monitored_conditions:
#  - _id
#  - _is_guest_by_uap
#  - _last_seen_by_uap
#  - _uptime_by_uap
#  - ap_mac
#  - assoc_time
#  - bytes-r
#  - ccq
#  - channel
#  - essid
#  - first_seen
#  - hostname
#  - idletime
#  - ip
#  - is_11r
#  - is_guest
#  - is_wired
#  - last_seen
#  - latest_assoc_time
#  - mac
#  - name
#  - noise
#  - noted
#  - oui
#  - powersave_enabled
#  - qos_policy_applied
#  - radio
#  - radio_proto
#  - rssi
#  - rx_bytes
#  - rx_bytes-r
#  - rx_packets
#  - rx_rate
#  - signal
#  - site_id
#  - tx_bytes
#  - tx_bytes-r
#  - tx_packets
#  - tx_power
#  - tx_rate
#  - uptime
